# Generated by Django 2.1.2 on 2018-10-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
