# Generated by Django 2.1.2 on 2018-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181021_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile_phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='qq',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='wechat',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
