# Generated by Django 2.1.2 on 2018-12-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountconfirmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmcode',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_confirm_code', to='account.Account'),
        ),
    ]
