# Generated by Django 2.1.2 on 2018-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20181005_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requirement',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
