# Generated by Django 2.1.2 on 2018-10-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20181025_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('active', '招募中'), ('finished', '报名截止')], default='active', max_length=32),
        ),
    ]
